QueueSystemWeb/Controllers/managerController.cs
using CrystalDecisions.CrystalReports.Engine;
using QueueSystemWeb.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QueueSystemWeb.Controllers
{
    public class managerController : Controller
    {
        QueueSystemDBEntities3 db = new QueueSystemDBEntities3();
        public ActionResult index()
        {
            ViewBag.fullname = Session["UserName"];
            ViewBag.userid = Session["UserID"];
            ViewBag.user_id = new SelectList(db.user, "Id");
            int UserID = Convert.ToInt32(Session["UserID"]);
            var user = db.user.SingleOrDefault(c => c.id == UserID);
            return View(user);
        }

        // GET: manger

        //*********************************************show all employees************************************************************/

        public ActionResult showemp()
        {
            var emp = db.user.Where(x => x.person_id == 3).ToList();
            List<user> user = new List<user>();
            if (emp.Equals(null))
            {
                return HttpNotFound();
            }
            else
            {
                foreach (user x in emp)
                {
                    user.Add(x);
                }

                ViewBag.emp = emp;
                ViewBag.numberRow = emp.Count();
                return View();
            }
        }

        //*******************************************show organization*******************************************//
        public ActionResult showorg()
        {
            int UserID = Convert.ToInt32(Session["UserID"]);
            var manager = db.user.SingleOrDefault(c => c.id == UserID);
            var org_id = db.organization.SingleOrDefault(c => c.manger_id == manager.id).id;
            var organization = db.organization.SingleOrDefault(c => c.id == org_id);
            if (organization.Equals(null))
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.organization = organization;
                return View();
            }
        }



        //*****************************************************delete employee**********************************************/
 
        public ActionResult deleteuser(int id)
        {

            var user = db.user.SingleOrDefault(c => c.id == id);
            var deluser = db.user.Remove(user);
            db.SaveChanges();
            return RedirectToAction("showemp");
        }
        //*************************************************delete services*************************************************//
        public ActionResult deleteserv(int id)
        {
            var serv = db.Services_.SingleOrDefault(c => c.id == id);
            var org_id = db.organization.SingleOrDefault(c => c.id == serv.org_id).id;
            var delserv = db.Services_.Remove(serv);
            db.SaveChanges();
            return RedirectToAction("showservise/"+ org_id);
        }
        //*********************************************edit organization****************************************************************/

        [HttpGet]
        public ActionResult Editorg(int id)
        {
            var org = db.organization.Find(id);
            return View(org);
        }

        [HttpPost]
        public JsonResult Editorg(int id, string name)
        {
            var result = 0;
            var orgs = db.organization.Where(c => c.name == name).ToList();
            var org = db.organization.SingleOrDefault(c => c.id == id);
            orgs.Remove(org);
            if (orgs.Count() != 0)
            {
                result = 0;
            }
            else
            {
                org.name = name;
                db.SaveChanges();
                result = 1;
            }

            return Json(new { result, JsonRequestBehavior.AllowGet });
        }
        //*********************************************edit branch*********************************************//
        [HttpGet]
        public ActionResult Editbranch(int id)
        {
            var branch = db.Branch.Find(id);
            return View(branch);
        }

        [HttpPost]
        public ActionResult Editbranch(int id, string branch_location , string name)
        {

            var branch = db.Branch.SingleOrDefault(c => c.id == id);
            branch.branch_location = branch_location;
            branch.name = name;
            db.SaveChanges();
            return RedirectToAction("showbranch/"+branch.organization_id);
        }

        //*********************************************edit service*********************************************//
        [HttpGet]
        public ActionResult Editservice(int id)
        {
            var service = db.Services_.Find(id);
            return View(service);
        }

        [HttpPost]
        public JsonResult Editservice(int id, string name, TimeSpan starttime, TimeSpan endtime, TimeSpan breakStart, TimeSpan breakPeriod, TimeSpan period, int toFinish, int toExpire)
        {
            var services = db.Services_.Where(c => c.name == name).ToList();
            var serve = db.Services_.SingleOrDefault(c => c.id == id);
            services.Remove(serve);
            int result = 0;
            if (services.Count() != 0)
            {
                result = 0;
            }
            else
            {
                serve.starttime = starttime;
                serve.endtime = endtime;
                serve.period = period;
                serve.name = name;
                serve.breakStart = breakStart;
                serve.breakPeriod = breakPeriod;
                serve.toExpire = toExpire;
                serve.toFinish = toFinish;
                db.SaveChanges();
                result = 1;
            }


            return Json(new { result, JsonRequestBehavior.AllowGet });
        }
        //************************************************add employee************************************************************/
        //
        [HttpGet]
        public ActionResult Addemp()
        {           
            user User = new user();
            return View(User);
        }

        [HttpPost]
        public JsonResult Addemp(user emp)
        {
            ViewBag.fullname = Session["UserName"];
            ViewBag.userid = Session["UserID"];
            ViewBag.user_id = new SelectList(db.user, "Id");
            int UserID = Convert.ToInt32(Session["UserID"]);
            var manager = db.user.SingleOrDefault(c => c.id == UserID);
            var check = db.user.Where(c => c.username == emp.username);

            int result = 0;

            if (check.Count() != 0)
            {
                result = 0;
            }
            else
            {
                if (ModelState.IsValid)
                {
                    emp.person_id = 3;
                    emp.count = 0;
                    emp.block = false;
                    db.user.Add(emp);
                    db.SaveChanges();
                    var org_id = db.organization.SingleOrDefault(c => c.manger_id == manager.id).id;
                    var emp_service = new Emp_Org_Services
                    {
                        emp_id = emp.id,
                        org_id = org_id
                    };
                    db.Emp_Org_Services.Add(emp_service);
                    db.SaveChanges();
                    result = 1;
                }
                else
                {
                    result = -1;
                }
            }
            return Json(new { result, JsonRequestBehavior.AllowGet });
        }


        //************************************************AssignEmpToServices************************************************************//
        [HttpGet]
        public ActionResult AssignEmpToServices()
        {
            ViewBag.fullname = Session["UserName"];
            ViewBag.userid = Session["UserID"];
            ViewBag.user_id = new SelectList(db.user, "Id");
            int UserID = Convert.ToInt32(Session["UserID"]);
            var manager = db.user.SingleOrDefault(c => c.id == UserID);
            int org_id = db.organization.SingleOrDefault(c => c.manger_id == manager.id).id;
            var emps = db.Emp_Org_Services.Where(c => c.org_id == org_id).ToList();
            var branches = db.Branch.Where(c => c.organization_id == org_id).ToList();
            var services = db.Services_.Where(c => c.org_id == org_id).ToList();
            EmpsOrg EmpsOrg = new EmpsOrg();
            List<user> employees = new List<user>();
            foreach(var x in emps)
            {
                var e = db.user.SingleOrDefault(c => c.id == x.emp_id);
                var a= e.name;
                if (!employees.Contains(x.user))
                {
                    employees.Add(e);
                }
                
            }
            EmpsOrg.emps = employees;
            EmpsOrg.branches = branches;
            EmpsOrg.services = services;
            return View(EmpsOrg);
        }

        [HttpPost]
        public ActionResult AssignEmpToServices(EmpsOrg EmpsOrg)
        {
            string result = "";
            ViewBag.fullname = Session["UserName"];
            ViewBag.userid = Session["UserID"];
            ViewBag.user_id = new SelectList(db.user, "Id");
            int UserID = Convert.ToInt32(Session["UserID"]);
            var manager = db.user.SingleOrDefault(c => c.id == UserID);
            var org_id = db.organization.SingleOrDefault(c => c.manger_id == manager.id).id;
            var e = db.Emp_Org_Services.SingleOrDefault(c => c.emp_id == EmpsOrg.emp_id && c.branch_id == null && c.service_id == null);
            var e2 = db.Emp_Org_Services.Where(c => c.emp_id == EmpsOrg.emp_id).ToList();
            var check = 0;
            foreach (var x in e2)
            {

QueueSystemWeb/Views/manager/Addemp.cshtml
@model QueueSystemWeb.Models.user
@{
    ViewBag.Title = "Addemp";
}

<div class="header-top-area">
    <div class="fixed-header-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-1 col-md-6 col-sm-6 col-xs-12">
                    <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="admin-logo logo-wrap-pro">
                        <a href="#">
                            <img src="@Url.Content("~/Content/project/")img/logo/images2.png" alt="" />
                        </a>
                    </div>
                </div>

                <div class="col-lg-6 col-md-1 col-sm-1 col-xs-12">
                    <div class="header-top-menu tabl-d-n">
                        <ul class="nav navbar-nav mai-top-nav">

                            <li class="nav-item">
                                <a href="~/manager/AssignEmpToServices" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">اضافه موظف لخدمه</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <i class="fa big-icon fa-pie-chart"></i> عرض <span class="angle-down-topmenu"><i class="fa fa-angle-down"></i></span>
                                </a>

                                <div role="menu" class="dropdown-menu animated flipInX">
                                    <a href="~/manager/showemp" class="dropdown-item">الموظفين</a>
                                    <a href="~/manager/showempBlocked" class="dropdown-item">الموظفين المحظورين</a>
                                    <a href="~/manager/showempunBlocked" class="dropdown-item">الموظفين الغير محظورين</a>
                                    <a href="~/manager/showorg" class="dropdown-item">المنظمات</a>

                                </div>
                            <li class="nav-item">
                                <a href="~/manager/managerreport" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">التقرير</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="~/manger/EditProfile" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">تعديل الصفحه</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="~/manger/Index" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-backward"></i>
                                    <span class="mini-dn">رجوع</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                    <div class="header-right-info">
                        <ul class="nav navbar-nav mai-top-nav header-right-menu">

                            <li class="nav-item">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <span class="adminpro-icon adminpro-user-rounded header-riht-inf"></span>


                                </a>
                                <ul role="menu" class="dropdown-header-top author-log dropdown-menu animated flipInX">
                                    <li>
                                        <a href="~/employee/Index"><span class="adminpro-icon adminpro-user-rounded author-log-ic"></span>الصفحه الشخصيه</a>
                                    </li>
                                    <li>
                                        <a href="/Home/Logout" style="margin-left:20px"><span class="adminpro-icon adminpro-locked author-log-ic"></span>تسجيل الخروج</a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm("Addemp", "manager", FormMethod.Post, new { @id = "msform", @class = "adminpro-form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="login-form-area mg-t-30 mg-b-15">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3"></div>
            <form id="adminpro-register-form" class="adminpro-form">
                <div class="col-lg-6">
                    <div class="login-bg">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="logo">
                                    <a href="#">
                                        <img src="@Url.Content("~/Content/project/")img/logo/images2.jpg" alt="" />
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="login-title">
                                    <h1>اضافه موظف</h1>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="login-input-head">
                                    <p>الاسم بالكامل</p>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="login-input-area">
                                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                    <i class="fa fa-user login-user"style="left:90px"></i>
                                </div>
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="login-input-head">
                                    <p>اسم المستخدم</p>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="login-input-area">
                                 @Html.EditorFor(model => model.username, new { htmlAttributes = new { @class = "form-control" } })
                                    <i class="fa fa-user login-user"style="left:90px"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="login-input-head">
                                    <p>عنوان البريد</p>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="login-input-area">
                                    @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                                    <i class="fa fa-envelope login-user" aria-hidden="true"style="left:90px"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="login-input-head">
                                    <p>كلمه السر</p>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="login-input-area">
                                    @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" , @type="password"} })
                                    <i class="fa fa-lock login-user"style="left:90px"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="login-input-head">
                                    <p>رقم التلفون</p>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="login-input-area">
                                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                                    <i class="fa fa-phone login-user" aria-hidden="true"style="left:90px"></i>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="login-input-head">
                                    <p>النوع</p>
                                </div>
                            </div>
                            <div class="col-lg-8">
                                <div class="cart-group">
                                    <label class="radio">
                                        @Html.RadioButtonFor(model => model.gender, "Male")
                                        <i></i>ذكر
                                    </label>
                                    <label class="radio">
                                        @Html.RadioButtonFor(model => model.gender, "Female")<i ></i>انثي
                                    </label>

                                </div>
                            </div>
                         
                        </div>
              

                        <div class="row">
                            <div class="col-lg-4"></div>
                            <div class="col-lg-8">
                                <div class="login-button-pro">

                                    <button type="button" id="save" class="login-button login-button-rg" style="float:right">اضافه </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="col-lg-3"></div>
        </div>
    </div>
</div>
}

<script>
    $(document).ready(function () {

        //reserve
        $("#save").click(function () {
            myData = $("#msform").serialize();
            $.ajax({
                type: "POST",
                url: "/admin/Addmanger",
                data: myData,
                success: function (response) {
                    $("#msform").empty();
                    if (response.result == 0) {
                        alert("اسم المستخدم موجود بالفعل");
                        document.location.reload(true);
                        window.location.href = "Addemp";
                    }
                    else if (response.result == 1) {
                        alert("تم اضافة المستخدم");
                        document.location.reload(true);
                        window.location.href = "showemp";
                    }
                    else {
                        alert("البيانات المدخلة خطأ");
                        document.location.reload(true);
                        window.location.href = "Addemp";
                    }

                }

            })

        })

    })
</script>

QueueSystemWeb/Views/manager/Editbranch.cshtml
@model QueueSystemWeb.Models.Branch

@{
    ViewBag.Title = "Editbranch";
}
<div class="header-top-area">
    <div class="fixed-header-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-1 col-md-6 col-sm-6 col-xs-12">
                    <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="admin-logo logo-wrap-pro">
                        <a href="#">
                            <img src="@Url.Content("~/Content/project/")img/logo/log.png" alt="" />
                        </a>
                    </div>
                </div>

                <div class="col-lg-6 col-md-1 col-sm-1 col-xs-12">
                    <div class="header-top-menu tabl-d-n">
                        <ul class="nav navbar-nav mai-top-nav">


                            <li class="nav-item">
                                <a href="~/manager/Addemp" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">اضافه موظف</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="~/manager/AssignEmpToServices" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">اضافه موظف لخدمه</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <i class="fa big-icon fa-pie-chart"></i> عرض <span class="angle-down-topmenu"><i class="fa fa-angle-down"></i></span>
                                </a>

                                <div role="menu" class="dropdown-menu animated flipInX">
                                    <a href="~/manager/managerreport" class="dropdown-item">التقارير</a>
                                    <a href="~/manager/showempBlocked" class="dropdown-item">الموظفين المحظورين</a>
                                    <a href="~/manager/showempunBlocked" class="dropdown-item">الموظفين الغير محظورين</a>
                                    <a href="~/manager/showorg" class="dropdown-item">المنظمات</a>


                                </div>
                            </li>
                            <li class="nav-item">
                                <a href="~/manager/EditProfile" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">تعديل الصفحه</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="~/manager/Index" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-backward"></i>
                                    <span class="mini-dn">رجوع</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>



                        </ul>
                    </div>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                    <div class="header-right-info">
                        <ul class="nav navbar-nav mai-top-nav header-right-menu">

                            <li class="nav-item">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <span class="adminpro-icon adminpro-user-rounded header-riht-inf"></span>


                                </a>
                                <ul role="menu" class="dropdown-header-top author-log dropdown-menu animated flipInX">
                                    <li>
                                        <a href="~/employee/Index"><span class="adminpro-icon adminpro-user-rounded author-log-ic"></span>الصفحه الشخصيه</a>
                                    </li>
                                    <li>
                                        <a href="/Home/Logout" style="margin-left:20px"><span class="adminpro-icon adminpro-locked author-log-ic"></span>تسجيل الخروج</a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<center>
    <div class="login-form-area mg-t-30 mg-b-40" style="width:1200px;margin-left:300px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4"></div>
                <form id="adminpro-form" class="adminpro-form">
                    <div class="col-lg-4">
                        <div class="login-bg"style="width: 600px; height: 700px;">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="logo">
                                        <a href="#">
                                            <img src="@Url.Content("~/Content/project/")img/logo/images2.jpg" alt="" />
                                        </a>
                                    </div>
                                </div>
                            </div>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.id)
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="login-title">
                                        <h1>تعديل الفرع</h1>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="login-input-head">
                                        <p>اسم الفرع</p>
                                    </div>
                                </div>
                                <div class="col-lg-8">
                                    <div class="login-input-area">
                                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                    <div class="login-input-head">
                                        <p>موقع الفرع</p>
                                    </div>
                                </div>
                                <div class="col-lg-8">
                                    <div class="login-input-area">
                                      @Html.EditorFor(model => model.branch_location, new { htmlAttributes = new { @class = "form-control" } })    
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-4">
                                </div>
                                <div class="col-lg-8">
                                    <div class="login-button-pro">
                                      
                                        <button type="submit" class="login-button login-button-lg" style="float:right"><i class="fa big-icon fa fa-pencil"></i>  تعديل</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                <div class="col-lg-4"></div>
            </div>
        </div>
    </div>

</center>
}