QueueSystemWeb/Controllers/employeeController.cs
using QueueSystemWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace QueueSystemWeb.Controllers
{
    public class employeeController : Controller
    {
        QueueSystemDBEntities3 db = new QueueSystemDBEntities3();

        //*********************************************show requests*********************************************//


        public ActionResult index()
        {
            /////////////////
            List<Notification> allNotis = Get_Notification();
            ViewBag.allNotis = allNotis;
            var countUnseenNotis = Get_UnSeen_Notification().Count();
            ViewBag.countUnseenNotis = countUnseenNotis;
            /////////////////
            ViewBag.fullname = Session["UserName"];
            ViewBag.userid = Session["UserID"];
            ViewBag.user_id = new SelectList(db.user, "Id");
            int UserID = Convert.ToInt32(Session["UserID"]);
            var user = db.user.SingleOrDefault(c => c.id == UserID);
            return View(user);
        }

        [HttpGet]
        public ActionResult Showrequests()
        {
            ViewBag.fullname = Session["username"];
            ViewBag.userid = Session["userid"];
            ViewBag.user_id = new SelectList(db.user, "id");
            var zaft = int.Parse(Session["userid"].ToString());
            var empl = db.user.SingleOrDefault(y => y.id == zaft);

            /////////////////
            List<Notification> allNotis = Get_Notification();
            ViewBag.allNotis = allNotis;
            var countUnseenNotis = Get_UnSeen_Notification().Count();
            ViewBag.countUnseenNotis = countUnseenNotis;
            /////////////////

            var reqs = db.Request.Where(c => c.empoyee_id == zaft && c.state == "pending" || c.state == "rejected").ToList();
            ViewBag.reqs = reqs;
            return View();

        }

        //*********************************************show requirements uploaded for some request*********************************************//
        [HttpGet]
        public ActionResult ShowRequirements(int id)
        {
            /////////////////
            List<Notification> allNotis = Get_Notification();
            ViewBag.allNotis = allNotis;
            var countUnseenNotis = Get_UnSeen_Notification().Count();
            ViewBag.countUnseenNotis = countUnseenNotis;
            /////////////////

            var reqAtts = db.Request_attachement.Where(c => c.request_id == id).ToList();
            ViewBag.reqAtts = reqAtts;
            ViewBag.emp_id = db.Request.SingleOrDefault(c => c.id == id).empoyee_id;
            ViewBag.req_id = id;
            return View();
        }

        [HttpPost]
        public ActionResult ShowRequirements(int reqId, string notes, string state)
        {
            var req = db.Request.SingleOrDefault(c => c.id == reqId);
            req.state = state;
            req.notes = notes;
            db.SaveChanges();
            string message = "";
            if (req.state == "rejected")
            {
                message = "لقد تم رفض طلبك";
            }
            else
            {
                message = "لقد تم قبول طلبك";
            }
            Notification noti = new Notification
            {
                msg = message,
                seen = false,
                dateTime = DateTime.Now,
                type_noti = "replyrequest",
                emp_id = req.empoyee_id,
                client_id = req.user_id,
                type_noti_id = req.id
            };
            db.Notification.Add(noti);
            db.SaveChanges();
            var emp_id = db.Request.SingleOrDefault(c => c.id == reqId).empoyee_id;
            return RedirectToAction("Showrequests/" + emp_id);
        }



        //*********************************************reserve offline*********************************************//

        [HttpGet]
        public ActionResult Reserve()
        {
            ViewBag.fullname = Session["username"];
            ViewBag.userid = Session["userid"];
            ViewBag.user_id = new SelectList(db.user, "id");
            var zaft = int.Parse(Session["userid"].ToString());

            /////////////////
            List<Notification> allNotis = Get_Notification();
            ViewBag.allNotis = allNotis;
            var countUnseenNotis = Get_UnSeen_Notification().Count();
            ViewBag.countUnseenNotis = countUnseenNotis;
            /////////////////

            //var reqs = db.Request.Where(c => c.empoyee_id == zaft).ToList();
            var v = db.Emp_Org_Services.Where(c => c.emp_id == zaft).ToList();
            var org_id = v[0].org_id;

            ReservationOffline app = new ReservationOffline();
            app.services = db.Services_.Where(c => c.org_id == org_id).ToList();
            return View(app);
        }

        [HttpPost]
        public JsonResult Reserve(ReservationOffline app)
        {
            string dateTime = app.date + "T" + app.time;
            DateTime dt = Convert.ToDateTime(dateTime);
            if (dt < DateTime.Now)
            {
                return Json(new { result = 0 }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var zaft = int.Parse(Session["userid"].ToString());
                var reqs = db.Emp_Org_Services.Where(c => c.emp_id == zaft).ToList();
                var branch_id = reqs[0].branch_id;
                var user = new user { name = app.name, phone = app.phone };
                db.user.Add(user);
                db.SaveChanges();

                var appointment = new Appointments_
                {
                    time = dt,
                    user_id = user.id,
                    service_id = app.service_id,
                    branch_id = branch_id
                };
                db.Appointments_.Add(appointment);
                db.SaveChanges();
                return Json(new { result = 1 }, JsonRequestBehavior.AllowGet);
            }
        }


        public JsonResult ShowTime(string date, int service_id)
        {
            var zaft = int.Parse(Session["userid"].ToString());
            var emp = db.user.SingleOrDefault(y => y.id == zaft);
            var reqs = db.Emp_Org_Services.Where(c => c.emp_id == emp.id).ToList();
            var branch_id = reqs[0].branch_id;
            Services_ service = db.Services_.SingleOrDefault(c => c.id == service_id);
            TimeSpan workPeriod = (TimeSpan)service.endtime - (TimeSpan)service.starttime;
            int workPeriodMinutes = (int)workPeriod.TotalMinutes;
            TimeSpan period = (TimeSpan)service.period;
            int servicePeriodMinutes = (int)period.TotalMinutes;
            int numRoles = workPeriodMinutes / servicePeriodMinutes;
            List<TimeSpan> times = new List<TimeSpan>();
            TimeSpan start = (TimeSpan)service.starttime;
            TimeSpan breakStart = (TimeSpan)service.breakStart;
            TimeSpan breakPeriod = (TimeSpan)service.breakPeriod;
            int breakPeriodMinutes = (int)breakPeriod.TotalMinutes;
            int breakRoles = breakPeriodMinutes / servicePeriodMinutes;
            TimeSpan breakEnd = breakStart + breakPeriod;

            for (int i = 0; i <= numRoles - breakRoles; i++)
            {
                if (start == breakStart)
                {
                    start = breakEnd;
                }
                else
                {
                    times.Add(start);
                    start = start + period;
                }

            }



            var service_emps = db.Emp_Org_Services.Where(c => c.service_id == service_id && c.branch_id == branch_id).ToList();

            int emps = service_emps.Count();
            List<TimeSpan> allTimes = new List<TimeSpan>();
            for (int i = 0; i < emps; i++)
            {
                foreach (var x in times)
                {
                    allTimes.Add(x);
                }

            }

            var appointments = db.Appointments_.Where(x => x.service_id == service_id && x.branch_id == branch_id).ToList();
            foreach (var x in appointments)
            {
                string dt = ((DateTime)x.time).ToString("yyyy-MM-dd");
                if (date.Equals(dt))
                {
                    string t = ((DateTime)x.time).ToString("H:mm:ss");
                    TimeSpan ts = TimeSpan.Parse(t);
                    allTimes.Remove(ts);
                }
            }
            List<string> AllTimes = new List<string>();
            foreach (var a in allTimes)
            {
                AllTimes.Add(a.ToString());
            }
            return Json(AllTimes, JsonRequestBehavior.AllowGet);
        }


        //*************************************** get all unavailabe dates for service***************************************//
        [HttpGet]
        public ActionResult GetUnAvailableDates(int service_id)
        {
            var zaft = int.Parse(Session["userid"].ToString());
            var emp = db.user.SingleOrDefault(y => y.id == zaft);
            var reqs = db.Emp_Org_Services.Where(c => c.emp_id == emp.id).ToList();
            var branch_id = reqs[0].branch_id;
            List<string> dates = new List<string>();
            var apps = db.Appointments_.Where(c => c.branch_id == branch_id && c.service_id == service_id).ToList();
            foreach (var x in apps)
            {
                string date = ((DateTime)x.time).ToString("yyyy-MM-dd");
                dates.Add(date);
            }
            List<string> datesDistinct = dates.Distinct().ToList();
            List<string> unAvailableDates = new List<string>();
            List<string> availableDates = new List<string>();
            foreach (var x in datesDistinct)
            {
                var allTimes = ShowTime(x, service_id);

QueueSystemWeb/Views/employee/CheckAttend.cshtml
@{
    ViewBag.Title = "CheckAttend";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="display:none">
    @Session["UserID"];
    @Session["UserName"];
</div>

<div class="header-top-area">
    <div class="fixed-header-top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-1 col-md-6 col-sm-6 col-xs-12">
                    <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
                        <i class="fa fa-bars"></i>
                    </button>
                    <div class="admin-logo logo-wrap-pro">
                        <a href="#">
                            <img src="@Url.Content(" ~/Content/project/")img/logo/log.png" alt="" />
                        </a>
                    </div>
                </div>

                <div class="col-lg-6 col-md-1 col-sm-1 col-xs-12">
                    <div class="header-top-menu tabl-d-n">
                        <ul class="nav navbar-nav mai-top-nav">

                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <i class="fa fa-bell"></i>
                                    @if (@ViewBag.countUnseenNotis != 0)
                                    {
                                        <span style="background-color: red;color: white;font-size: 13px;position: absolute;top:10px;right: 10px;width:20px;height:20px;border-radius:100%;text-align:center;">@ViewBag.countUnseenNotis</span>
                                    }
                                </a>

                                <div role="menu" class="dropdown-menu animated flipInX" style="overflow-y:scroll; height:400px;width:400px;">
                                    <div style="width:382px;background-color:#ff8196;border:groove;">
                                        <p style="text-align:center;margin-left:5px; font-size:30px;">الاشعارات</p>
                                    </div>
                                    @foreach (var x in ViewBag.allNotis)
                                    {
                                        if (x.seen == true)
                                        {
                                            <a class="dropdown-item" id="noti" onclick="showNoti(@x.Id)">

                                                <span>Client</span>
                                                <span>sent a </span>
                                                <span>@x.type_noti </span>
                                                <span>@x.msg </span>
                                                <span>in </span>
                                                <span>@x.dateTime</span>
                                            </a>
                                        }
                                        else
                                        {
                                            <a class="dropdown-item" id="noti" onclick="showNoti(@x.Id)">
                                                <span>Client </span>
                                                <span>sent a </span>
                                                <span>@x.type_noti : " </span>
                                                <span>@x.msg "</span>
                                                <span>in : "</span>
                                                <span>@x.dateTime " </span>
                                                <span id="seen" style="background-color: dodgerblue;width:7px;height:7px;border-radius:100%;position: absolute;right:3px;"></span>
                                            </a>
                                        }

                                    }
                                    <div style="background-color:#ff8196;color:black;width:382px;border:groove;display:inline-block;">
                                        <a style="text-align:center;display:block;" onclick="seeAll()">See All</a>
                                    </div>
                                </div>
                            </li>



                           
                            <li class="nav-item dropdown">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <i class="fa big-icon fa-eye"></i> عرض <span class="angle-down-topmenu"><i class="fa fa-angle-down"></i></span>
                                </a>

                                <div role="menu" class="dropdown-menu animated flipInX">
                                    <a href="/employee/ReplayComplainOrInquire" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                        <i class="fa fa-comment login-user"></i>
                                        <span class="mini-dn">الرسائل</span>
                                        <span class="indicator-right-menu mini-dn"></span>
                                    </a>
                                    <a href="/employee/Showrequests" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                        <i class="fa fa-dropbox"></i>
                                        <span class="mini-dn">الطالبات</span>
                                        <span class="indicator-right-menu mini-dn"></span>
                                    </a>

                                    <a href="/employee/showblock" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                        <i class="fa fa-expeditedssl"></i>
                                        <span class="mini-dn">العملاء المحظورين</span>
                                        <span class="indicator-right-menu mini-dn"></span>
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a href="/employee/Reserve" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <i class="fa fa-ticket"></i>
                                    <span class="mini-dn">حجز</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="/employee/EditProfile" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <i class="fa big-icon fa-edit"></i>
                                    <span class="mini-dn">تعديل الصفحه الشخصيه</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="~/employee/Index" role="button" aria-expanded="false">
                                    <i class="fa big-icon fa-backward"></i>
                                    <span class="mini-dn">رجوع</span>
                                    <span class="indicator-right-menu mini-dn"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                       <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                    <div class="header-right-info">
                        <ul class="nav navbar-nav mai-top-nav header-right-menu">

                            <li class="nav-item">
                                <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
                                    <span class="adminpro-icon adminpro-user-rounded header-riht-inf"></span>


                                </a>
                                <ul role="menu" class="dropdown-header-top author-log dropdown-menu animated flipInX">
                                    <li>
                                        <a href="/employee/EditProfile"><span class="adminpro-icon adminpro-user-rounded author-log-ic"></span>الصفحه الشخصيه</a>
                                    </li>
                                    <li>
                                        <a href="/Home/Logout" style="margin-left:20px"><span class="adminpro-icon adminpro-locked author-log-ic"></span>تسجيل الخروج</a>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<div style="margin-right:50px">
    <div class="sparkline8-hd" style="margin-top:50px">
        <div class="main-sparkline8-hd">
            <h1>مراجعه الحضور</h1>

        </div>
    </div>
    <div class="sparkline8-graph">
        <div class="static-table-list">

            <table class="table" data-toggle="table">
                <thead style="background-color:#ebebeb">
                    <tr>
                        @foreach (var x in ViewBag.service_names)
                        {
                            <th> خدمه : @x </th>
                        }
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        @foreach (var x in ViewBag.service_apps)
                        {
                            <td>
                                <table id="myTable">
                                    @for (int i = 0; i < x.Count; i++)
                                    {
                                        <tr id="raw">
                                            <td>@x[i].user.name</td>
                                            <td>@x[i].time.ToString("HH:mm:ss")</td>
                                            <td>
                                                @using (Html.BeginForm("CheckAttend", "employee", FormMethod.Post, new { enctype = "multipart/form-data", id = "msform" }))
                                                {
                                                    <input type="hidden" name="user_id" id="user_id" value="@x[i].user.id" />
                                                    <input type="hidden" name="app_id" id="check" value="@x[i].id" />
                                                    <button id="btn" name="check" value="1" type="submit"  class="login-button login-button-lg">نعم</button>
                                                    <button id="btn" name="check" value="0" type="submit" class="login-button login-button-lg">لا</button>
                                                }
                                            </td>
                                        </tr>
                                    }
                                </table>
                            </td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        showNoti(n);
        function showNoti(n) {
            document.location.reload(true);
            window.location.href = "ShowNotiReferece?noti_id=" + n;    
        }

        function seeAll() {
            document.location.reload(true);
            window.location.href = "Get_All_Notification";    
        }

    </script>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>